VisionBoard/Models/Measurement.cs
using System.ComponentModel.DataAnnotations;
using VisionBoard.Utils;

namespace VisionBoard.Models
{
    public partial class Measurement
    {
        public int Id { get; set; }
        public string Type { get; set; }

        [Required(ErrorMessage = AppConstants.CurrentValueRequiredMessage)]
        [Range(0, 40000000, ErrorMessage = AppConstants.CurrentValueLengthMessage)]
        public int CurrentValue { get; set; }

        [Required(ErrorMessage = AppConstants.TotalValueRequiredMessage)]
        [Range(1, 40000000, ErrorMessage = AppConstants.TotalValueLengthMessage)]
        public int TotalValue { get; set; }

        [Required(ErrorMessage = AppConstants.UnitRequiredMessage)]
        [MaxLength(50, ErrorMessage = AppConstants.UnitLengthMessage)]
        public string Unit { get; set; }

        public virtual Goal Goal { get; set; }
    }
}

VisionBoard/Controllers/MeasurementsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VisionBoard.DAL;
using VisionBoard.Models;
using VisionBoard.Utilis;

namespace VisionBoard.Controllers
{
    public class MeasurementsController : Controller
    {
        private readonly IGoalRepository goalRepo;
        private readonly IErrorLogRepository errorLogRepository;
        private readonly IMeasurementRepository MeasurementRepo;

        public MeasurementsController(IMeasurementRepository measurementRepo, IGoalRepository goalRepo, IErrorLogRepository errorLogRepository)
        {
            MeasurementRepo = measurementRepo;
            this.goalRepo = goalRepo;
            this.errorLogRepository = errorLogRepository;
        }


        // GET: Mesurements
        public async Task<IActionResult> Index()
        {
            try
            {
                var measurements = await MeasurementRepo.GetAllMeasurements();
                return View(measurements);
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Mesurements/Details/5        
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                if (id != null)
                {
                    var measurement = await MeasurementRepo.GetMeasurement((int)id);

                    if (measurement != null)
                    {
                        return View(measurement);
                    }
                }

                return NotFound();
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Mesurements/Create
        public async Task<IActionResult> Create(int? goalId)
        {
            try
            {
                ViewData["GoalId"] = goalId;
                return View();
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // POST: Mesurements/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int goalId, [Bind("Id,Type,CurrentValue,TotalValue,Unit")] Measurement measurement)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Measurement mesurement = await MeasurementRepo.AddMeasurement(measurement);
                    Goal goal = await goalRepo.GetGoal(goalId);
                    goal.MeasurementId = mesurement.Id;
                    await goalRepo.UpdateGoal(goal);
                    return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "Details", measurement) });
                }

                ViewData["GoalId"] = goalId;
                return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Create", measurement) });
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Mesurements/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id != null)
                {
                    var measurement = await MeasurementRepo.GetMeasurement((int)id);
                    if (measurement != null)
                    {
                        return View(measurement);
                    }
                }
                return NotFound();
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // POST: Measurements/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GoalId")] int goalId, [Bind("Id,Type,CurrentValue,TotalValue,Unit")] Measurement measurement)
        {
            try
            {
                if (id != measurement.Id)
                {
                    return NotFound();
                }
                ViewData["GoalId"] = goalId;

                if (ModelState.IsValid)
                {
                    var mesurement = await MeasurementRepo.UpdateMeasurement(measurement);
                    Goal goal = await goalRepo.GetGoal(goalId);
                    goal.MeasurementId = mesurement.Id;
                    await goalRepo.UpdateGoal(goal);
                    return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "Details", measurement) });
                }
                return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", measurement) });
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Mesurements/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                var measurement = await MeasurementRepo.GetMeasurement((int)id);

                if (measurement == null)
                {
                    return NotFound();
                }

                return View(measurement);
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // POST: Measurements/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await MeasurementRepo.DeleteMeasurement(id);
                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        private async Task<bool> MeasurementExists(int id)
        {
            try
            {
                return await MeasurementRepo.IsMeasurementExist(id);
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return false;

        }


    }
}

VisionBoard/Views/Measurements/Create.cshtml
@model VisionBoard.Models.Measurement

@{
    ViewData["Title"] = "Create";
    Layout = null;
}

<div class="row">
    <div class="col-md-12">
        <form asp-controller="Measurements" asp-action="Create" asp-route-goalId="@ViewBag.GoalId" onsubmit="return AddorEditMeasurement(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Type" class="control-label"></label><br />
                        <input type="radio" asp-for="Type" value="By Value" />By Value &nbsp;&nbsp;
                        <input type="radio" asp-for="Type" value="By Steps" />By Steps<br />
                        <span asp-validation-for="Type" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="CurrentValue" class="control-label"></label>
                        <input asp-for="CurrentValue" class="form-control" />
                        <span asp-validation-for="CurrentValue" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="TotalValue" class="control-label"></label>
                        <input asp-for="TotalValue" class="form-control" />
                        <span asp-validation-for="TotalValue" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Unit" class="control-label"></label>
                        <select id="select-unit" class="form-control" onchange='NewUnit(this.value);'>
                            <option value="Unit">Unit</option>
                            <option value="Inche">Inch</option>
                            <option value="Meter">Meter</option>
                            <option value="Kilometer">Kilometer</option>
                            <option value="pound">pound</option>
                            <option value="centimeter">centimeter</option>
                            <option value="Kilogram">Kilogram</option>
                            <option value="others">others</option>
                        </select>
                        <input type="text" name="Unit" id="text-unit" class="form-control" style='display:none;' />
                        <span asp-validation-for="Unit" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VisionBoard/Views/Measurements/Delete.cshtml
@model VisionBoard.Models.Measurement

@{
    ViewData["Title"] = "Delete";
    Layout = null;
}

<h3>Are you sure you want to Remove Progress Tracking?</h3>
<div class="row p-4">
    <div class="col-md-12">
        <div class="row p-2 text-center">
            <div class="col-md-10">
                @{
                    string progress = (Math.Round((double)(100 * Model.CurrentValue) / Model.TotalValue)).ToString() + "%";
                    <div class="progress">
                        <div class="progress-bar bg-success" role="progressbar" style="width: @progress" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
                            @progress
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="row p-2 text-center">
            <div class="col-md-5">
                <span class="label font-weight-bold">Completed : </span>
                <span>@Model.CurrentValue.ToString()&nbsp;@(Model.Type=="By Steps"?"Steps": Model.Unit )</span>
            </div>
            <div class="col-md-5">
                <div class="float-right">
                    <span class="label font-weight-bold">Total : </span>
                    <span>@Model.TotalValue.ToString()&nbsp;@(Model.Type=="By Steps"?"Steps": Model.Unit )</span>
                </div>
            </div>
        </div>

    </div>
</div>
<div>
    <a class="btn btn-danger" onclick="DeleteMeasurement('@Url.Action("Delete", "Measurements", new { id=@Model.Id})')">Delete</a>
</div>

VisionBoard/Views/Measurements/Details.cshtml
@model VisionBoard.Models.Measurement

@Html.Hidden("MeasurementId", Model.Id)
<div class="row">
    <div class="col-md-12">
        <div class="row p-2">
            <div class="col-md-10">
                @{
                    string progress = (Math.Round((double)(100 * Model.CurrentValue) / Model.TotalValue)).ToString() + "%";
                    <div class="progress">
                        <div class="progress-bar bg-success" role="progressbar" style="width: @progress" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
                            @progress
                        </div>
                    </div>
                }
            </div>
            <div class="col-md-2">
                <a onclick="showInPopup('@Url.Action("Edit","Measurements",new { id = @Model.Id },Context.Request.Scheme)','Edit Mesurement')"><i class="fa-solid fa-pen-to-square text-warning"></i></a>
            </div>
        </div>
        <div class="row p-2">
            <div class="col-md-6">
                <span class="label font-weight-bold">Completed : </span>
                <span>@Model.CurrentValue.ToString()&nbsp;@(Model.Type=="By Steps"?"Steps": Model.Unit )</span>
            </div>
            <div class="col-md-6">
                <div class="float-right">
                    <span class="label font-weight-bold">Total : </span>
                    <span>@Model.TotalValue.ToString()&nbsp;@(Model.Type=="By Steps"?"Steps": Model.Unit )</span>
                </div>
            </div>
        </div>
    </div>
</div>

VisionBoard/Views/Measurements/Edit.cshtml
@model VisionBoard.Models.Measurement

@{
    ViewData["Title"] = "Edit";
    Layout = null;
    if (Model.Goal != null)
    {
        ViewBag.GoalId = Model.Goal.Id;
    }
}

<div class="row">
    <div class="col-md-12">
        <form asp-controller="Measurements" asp-action="Edit" asp-route-id="@Model.Id" onsubmit="return AddorEditMeasurement(this);">
            <input type="hidden" name="GoalId" value="@ViewBag.GoalId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Type" class="control-label"></label><br />
                        <input type="radio" asp-for="Type" value="By Value" />By Value &nbsp;&nbsp;
                        <input type="radio" asp-for="Type" value="By Steps" />By Steps<br />
                        <span asp-validation-for="Type" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="CurrentValue" class="control-label"></label>
                        <input asp-for="CurrentValue" class="form-control" />
                        <span asp-validation-for="CurrentValue" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="TotalValue" class="control-label"></label>
                        <input asp-for="TotalValue" class="form-control" />
                        <span asp-validation-for="TotalValue" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Unit" class="control-label"></label>
                        <select id="select-unit" class="form-control" onchange='NewUnit(this.value);'>
                            <option value="@Model.Unit">@Model.Unit</option>
                            <option value="Inche">Inch</option>
                            <option value="Meter">Meter</option>
                            <option value="Kilometer">Kilometer</option>
                            <option value="pound">pound</option>
                            <option value="centimeter">centimeter</option>
                            <option value="Kilogram">Kilogram</option>
                            <option value="others">others</option>
                        </select>
                        <input asp-for="Unit" type="text" name="Unit" id="text-unit" class="form-control" style='display:none;' />
                        <span asp-validation-for="Unit" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}