VisionBoard/Models/Step.cs
using System;
using System.ComponentModel.DataAnnotations;
using VisionBoard.Utils;

#nullable disable

namespace VisionBoard.Models
{
    public partial class Step
    {
        public int Id { get; set; }

        [Display(Name = "Step Name")]
        [Required(ErrorMessage = AppConstants.NameRequiredMessage)]
        [MaxLength(50, ErrorMessage = AppConstants.NameLengthMessage)]
        public string Name { get; set; }

        [MaxLength(600, ErrorMessage = AppConstants.DescriptionLengthMessage)]
        public string Description { get; set; }

        [Required(ErrorMessage = AppConstants.WeightRequiredMessage)]
        [Range(1, 40000000, ErrorMessage = AppConstants.WeightLengthMessage)]
        public int Weight { get; set; }

        [Display(Name = "Due Date")]
        public DateTime? DueDate { get; set; }
        public bool Status { get; set; }

        [Display(Name = "Goal Name")]
        public int GoalId { get; set; }

        public virtual Goal Goal { get; set; }
    }
}

VisionBoard/Controllers/StepsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VisionBoard.DAL;
using VisionBoard.Models;
using VisionBoard.Utilis;

namespace VisionBoard.Controllers
{
    public class StepsController : Controller
    {
        private readonly IStepRepository stepsRepo;
        private readonly IGoalRepository goalRepo;
        private readonly IErrorLogRepository errorLogRepository;

        public StepsController(IStepRepository stepsRepo, IGoalRepository goalRepo, IErrorLogRepository errorLogRepository)
        {
            this.stepsRepo = stepsRepo;
            this.goalRepo = goalRepo;
            this.errorLogRepository = errorLogRepository;
        }


        // GET: Steps
        public async Task<IActionResult> Index(int? goalId)
        {
            try
            {
                var steps = await stepsRepo.GetAllSteps();
                return View(steps);
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Steps/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                if (id != null)
                {
                    var step = await stepsRepo.GetStep((int)id);
                    if (step != null)
                    {
                        return View(step);
                    }
                }
                return NotFound();
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Steps/Create
        public async Task<IActionResult> Create(int? goalId)
        {
            try
            {
                if (goalId == null)
                {
                    ViewData["CurrentGoalId"] = goalId;
                    ViewData["GoalId"] = new SelectList(await goalRepo.GetAllGoalsWithoutInnerObjects(), "Id", "Name");
                }
                else
                {
                    IEnumerable<Goal> goal = new List<Goal>()
                {
                    await goalRepo.GetGoal((int)goalId)
                };
                    ViewData["GoalId"] = new SelectList(goal, "Id", "Name");
                    ViewData["CurrentGoalId"] = goalId;
                }

                return View();
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // POST: Steps/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? currentGoalId, [Bind("Id,Name,Description,Weight,DueDate,GoalId")] Step step)
        {
            try
            {
                step.Status = false;

                if (ModelState.IsValid)
                {
                    await stepsRepo.AddStep(step);

                    IEnumerable<Step> steps = new List<Step>();
                    if (currentGoalId == null)
                    {
                        steps = await stepsRepo.GetAllSteps();
                    }
                    else
                    {
                        ViewData["CurrentGoalId"] = currentGoalId;
                        steps = await stepsRepo.GetAllSteps((int)currentGoalId);
                    }

                    return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "IndexSteps", steps) });
                }

                if (currentGoalId == null)
                {
                    ViewData["GoalId"] = new SelectList(await goalRepo.GetAllGoalsWithoutInnerObjects(), "Id", "Name");
                }
                else
                {
                    IEnumerable<Goal> goal = new List<Goal>()
                    {
                        await goalRepo.GetGoal((int)currentGoalId)
                    };
                    ViewData["CurrentGoalId"] = currentGoalId;
                    ViewData["GoalId"] = new SelectList(goal, "Id", "Name");
                }

                return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Create", step) });
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Steps/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id != null)
                {
                    var step = await stepsRepo.GetStep((int)id);
                    if (step != null)
                    {
                        ViewData["GoalId"] = new SelectList(await goalRepo.GetAllGoalsWithoutInnerObjects(), "Id", "Name", step.GoalId);
                        return View(step);
                    }
                }
                return NotFound();
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // POST: Steps/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Weight,DueDate,Status,GoalId")] Step step)
        {
            try
            {
                if (id != step.Id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    await stepsRepo.UpdateStep(step);
                    var steps = await stepsRepo.GetAllSteps(step.GoalId);
                    return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "IndexSteps", steps) });
                }
                ViewData["GoalId"] = new SelectList(await goalRepo.GetAllGoalsWithoutInnerObjects(), "Id", "Name", step.GoalId);
                return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", step) });
            }
            catch (Exception ex)
            {
                if (!await StepExists(step.Id))
                {
                    return NotFound();
                }
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Steps/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id != null)
                {
                    var step = await stepsRepo.GetStep((int)id);
                    if (step != null)
                    {
                        return View(step);
                    }
                }
                return NotFound();
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // POST: Steps/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await stepsRepo.DeleteStep(id);
                var steps = await stepsRepo.GetAllSteps();
                return Json(new { success = true, html = Helper.RenderRazorViewToString(this, "IndexSteps", steps) });
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        private async Task<bool> StepExists(int id)
        {
            try
            {
                return await stepsRepo.IsStepExist(id);
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return false;

        }


    }
}

VisionBoard/Views/Steps/Create.cshtml
@model VisionBoard.Models.Step

@{
    ViewData["Title"] = "Create";
    Layout = null;
}


<div class="row">
    <div class="col-md-12">
        <form asp-controller="Steps" asp-action="Create" asp-route-currentGoalId="@ViewBag.CurrentGoalId" onsubmit="return AddorEditStep(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="GoalId" text="Goal Name" class="control-label"></label>
                        <select asp-for="GoalId" class="form-control" asp-items="ViewBag.GoalId"></select>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="=row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea asp-for="Description" rows="5" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Weight" class="control-label"></label>
                            <input asp-for="Weight" class="form-control" />
                            <span asp-validation-for="Weight" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="DueDate" class="control-label"></label>
                            <input asp-for="DueDate" class="form-control" />
                            <span asp-validation-for="DueDate" class="text-danger"></span>
                        </div>
                    </div>                    
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
</form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VisionBoard/Views/Steps/Delete.cshtml
@model VisionBoard.Models.Step

@{
    ViewData["Title"] = "Delete";
    Layout = null;
}
<div class="p-3">
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <div class="row mt-2 p-4">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-sm-12">
                        <span class="label font-weight-bold">Name : </span>
                        <span>@Model.Name </span>
                    </div>
                </div>
                <div class="row pt-3">
                    <div class="col-sm-12">
                        <span class="label font-weight-bold">Description : </span>
                        <span>@Model.Description </span>
                    </div>
                </div>
                <div class="row pt-3">
                    <div class="col-sm-6">
                        <span class="label font-weight-bold">Weight : </span>
                        <span>@Model.Weight </span>
                    </div>
                    <div class="col-sm-6">
                        <span class="label font-weight-bold">Due Date : </span>
                        <span>@Model.DueDate.Value.Date.ToString("dd/MM/yyyy") </span>
                    </div>
                </div>
                <div class="row pt-3">
                    <div class="col-sm-12">
                        <span class="label font-weight-bold">Status : </span>
                        <span>@(Model.Status==true?"Completed":"Pending") </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a class="btn btn-danger" onclick="DeleteStep('@Url.Action("Delete", "Steps", new { id=@Model.Id})')">Delete</a>
</div>

VisionBoard/Views/Steps/Details.cshtml
@model VisionBoard.Models.Step

@{
    ViewData["Title"] = "Details";
    Layout = null;
}

<div>
    <div class="row mt-2 p-4">
        <div class="col-md-12">
            <div class="row">
                <div class="col-sm-12">
                    <span class="label font-weight-bold">Name : </span>
                    <span>@Model.Name </span>
                </div>
            </div>
            <div class="row pt-3">
                <div class="col-sm-12">
                    <span class="label font-weight-bold">Description : </span>
                    <span>@Model.Description </span>
                </div>
            </div>
            <div class="row pt-3">
                <div class="col-sm-6">
                    <span class="label font-weight-bold">Weight : </span>
                    <span>@Model.Weight </span>
                </div>
                <div class="col-sm-6">
                    <span class="label font-weight-bold">Due Date : </span>
                    <span>@Model.DueDate.Value.Date.ToString("dd/MM/yyyy") </span>
                </div>
            </div>
            <div class="row pt-3">
                <div class="col-sm-12">
                    <span class="label font-weight-bold">Status : </span>
                    <span>@(Model.Status==true?"Completed":"Pending") </span>
                </div>
            </div>
        </div>
    </div>
</div>

VisionBoard/Views/Steps/Edit.cshtml
@model VisionBoard.Models.Step

@{
    ViewData["Title"] = "Edit";
    Layout = null;
}

<div class="row">
    <div class="col-md-12">
        <form asp-controller="Steps" asp-action="Edit" asp-route-id="@Model.Id" onsubmit="return AddorEditStep(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="GoalId" class="control-label"></label>
                        <select asp-for="GoalId" class="form-control" asp-items="ViewBag.GoalId"></select>
                        <span asp-validation-for="GoalId" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">                    
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea asp-for="Description" rows="5" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Weight" class="control-label"></label>
                        <input asp-for="Weight" class="form-control" />
                        <span asp-validation-for="Weight" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="DueDate" class="control-label"></label>
                        <input asp-for="DueDate" class="form-control" />
                        <span asp-validation-for="DueDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group form-check">                        
                        <span class="label ">Status </span>
                        <label class="radio">
                            <input type="radio" name="Status" value="true" @(Model.Status ? "Checked" : "")>Completed
                        </label>
                        <label class="radio">
                            <input type="radio" name="Status" value="false" @(!Model.Status ? "Checked" : "")>Pending
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VisionBoard/Views/Steps/Index.cshtml
@model IEnumerable<VisionBoard.Models.Step>

@{
    ViewData["Title"] = "Index";
}
<div class="mt-4">
    <h2>Steps</h2>
    <div class="mt-4">
        <div id="list-steps" class="steps-table">
            @await Html.PartialAsync("IndexSteps", Model)
        </div>
    </div>    
</div>

VisionBoard/Views/Steps/IndexSteps.cshtml
@model IEnumerable<VisionBoard.Models.Step>

<table class="table">
    <thead>
        <tr>
            <th width="15%">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th width="40%">
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th width="5%">
                @Html.DisplayNameFor(model => model.Weight)
            </th>
            <th width="5%">
                @Html.DisplayNameFor(model => model.DueDate)
            </th>
            <th width="10%">
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th width="10%">
                @Html.DisplayNameFor(model => model.Goal)
            </th>
            <th width="15%">
                <a onclick="showInPopup('@Url.Action("Create","Steps",new { goalId = ViewBag.goalId },Context.Request.Scheme)','Add Step')" class="btn btn-success text-white"> Add step</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="col-description">
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Weight)
                </td>
                <td>
                    @Html.Label("DueDate", item.DueDate.Value.Date.ToShortDateString())
                </td>
                <td>
                    @Html.Label("Status", item.Status ? "Completed" : "Pending")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Goal.Name)
                </td>
                <td>
                    <a onclick="showInPopup('@Url.Action("Edit","Steps",new { id = @item.Id },Context.Request.Scheme)','Edit Step')"><i class="fa-solid fa-pen-to-square text-warning"></i></a>
                    <a onclick="showInPopup('@Url.Action("Details","Steps", new { id = @item.Id }, Context.Request.Scheme)','View Step')"><i class="fa-solid fa-eye text-info pl-2"></i></a>
                    <a onclick="showInPopup('@Url.Action("Delete","Steps", new { id = @item.Id }, Context.Request.Scheme)','Delete Step')"><i class="fa-solid fa-trash-can text-danger pl-2"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>
@{
    if (Model.Count() == 0)
    {
        <div class="text-center pb-3">
            <p class="h6">No Steps Found!, To Add The Steps Required To Complete This Goal Click The Add Step Button.</p>
        </div>
    }
}