VisionBoard/Models/Reward.cs
#nullable disable

using System.ComponentModel.DataAnnotations;
using VisionBoard.Utils;

namespace VisionBoard.Models
{
    public partial class Reward
    {
        public int Id { get; set; }

        [Required(ErrorMessage = AppConstants.NameRequiredMessage)]
        [MaxLength(50, ErrorMessage = AppConstants.NameLengthMessage)]
        public string Name { get; set; }

        [MaxLength(600, ErrorMessage = AppConstants.DescriptionLengthMessage)]
        public string Description { get; set; }

        public string PictureUrl { get; set; }
        public bool Status { get; set; }

        public virtual Goal Goal { get; set; }

    }
}

VisionBoard/Controllers/RewardsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using VisionBoard.DAL;
using VisionBoard.Models;
using VisionBoard.Utilis;

namespace VisionBoard.Controllers
{
    public class RewardsController : Controller
    {

        private readonly IRewardRepository rewardsRepo;
        private readonly IGoalRepository goalRepo;
        private readonly IErrorLogRepository errorLogRepository;

        public RewardsController(IRewardRepository rewardsRepo, IGoalRepository goalRepo, IErrorLogRepository errorLogRepository)
        {
            this.rewardsRepo = rewardsRepo;
            this.goalRepo = goalRepo;
            this.errorLogRepository = errorLogRepository;
        }


        // GET: Rewards
        public async Task<IActionResult> Index()
        {
            try
            {
                var rewards = await rewardsRepo.GetAllRewards();
                return View(rewards);
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Rewards/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                if (id != null)
                {
                    var reward = await rewardsRepo.GetReward((int)id);

                    if (reward != null)
                    {
                        return View(reward);
                    }
                }

                return NotFound();
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Rewards/Create
        public async Task<IActionResult> Create(string source)
        {
            try
            {
                ViewData["GoalId"] = new SelectList(await goalRepo.GetAllGoalsWithoutInnerObjects(), "Id", "Name");
                ViewBag.Source = source;
                return View();
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // POST: Rewards/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string source, [Bind("Id,Name,Description,GoalId,PictureUrl")] Reward reward)
        {
            try
            {
                //achieved reward or not
                reward.Status = false;
                if (ModelState.IsValid)
                {
                    var newReward = await rewardsRepo.AddReward(reward);

                    if (source == "DropDown")
                    {
                        return Json(new { isValid = true, Source = source, Id = newReward.Id, Name = newReward.Name });
                    }
                    else
                    {
                        var rewards = await rewardsRepo.GetAllRewards();
                        return Json(new { isValid = true, source = "Index", html = Helper.RenderRazorViewToString(this, "IndexRewards", rewards) });
                    }
                }
                ViewBag.Source = source;
                return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Create", reward) });
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Rewards/Edit/5
        public async Task<IActionResult> Edit(int? id, string source)
        {
            try
            {
                if (id != null)
                {
                    var reward = await rewardsRepo.GetReward((int)id);

                    if (reward != null)
                    {
                        ViewBag.Source = source;
                        return View(reward);
                    }
                }

                return NotFound();
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // POST: Rewards/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, string source, [Bind("Id,Name,Description,GoalId,PictureUrl,Status")] Reward reward)
        {
            try
            {
                if (id != reward.Id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    var newReward = await rewardsRepo.UpdateReward(reward);

                    if (source == "DropDown")
                    {
                        return Json(new { isValid = true, Source = source, Id = newReward.Id, Name = newReward.Name });
                    }
                    else
                    {
                        var rewards = await rewardsRepo.GetAllRewards();
                        return Json(new { isValid = true, source = "Index", html = Helper.RenderRazorViewToString(this, "IndexRewards", rewards) });
                    }

                }
                return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", reward) });
            }
            catch (Exception ex)
            {
                if (!await RewardExists(reward.Id))
                {
                    return NotFound();
                }
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Rewards/Delete/5
        public async Task<IActionResult> Delete(int? id, string source)
        {
            try
            {
                if (id != null)
                {
                    var reward = await rewardsRepo.GetReward((int)id);

                    if (reward != null)
                    {
                        ViewBag.Source = source;
                        return View(reward);
                    }
                }
                return NotFound();
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // POST: Rewards/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id, string source)
        {
            try
            {
                var newReward = await rewardsRepo.DeleteReward(id);

                if (source == "DropDown")
                {
                    return Json(new { isValid = true, Source = source, Id = newReward.Id, Name = newReward.Name });
                }
                else
                {
                    var rewards = await rewardsRepo.GetAllRewards();
                    return Json(new { isValid = true, source = "Index", html = Helper.RenderRazorViewToString(this, "IndexRewards", rewards) });
                }
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        private async Task<bool> RewardExists(int id)
        {
            try
            {
                return await rewardsRepo.IsRewardExist(id);
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return false;

        }


    }
}

VisionBoard/Views/Rewards/Create.cshtml
@model VisionBoard.Models.Reward

@{
    ViewData["Title"] = "Create";
    Layout = null;
}

<div class="row">    
<div class="col-md-12">
    <div class="row">
        <div class="col-md-12 text-center">
            <div id="crop-reward-image" style="display:none">
                @await Html.PartialAsync("~/Views/Media/CustomCrop.cshtml", "RewardImage")
            </div>
        </div>
    </div>
    <form asp-controller="Rewards" asp-action="Create" onsubmit="return AddorEditReward(this);">
        <input type="hidden" name="source" id="source" value="@ViewBag.Source" />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            <div class="col-md-12 text-center">
                <div class="reward-img">
                    <img src="~/images/reward_noimage.png" asp-append-version="true" id="reward-img">
                    <input type="hidden" id="reward-picture-url" name="PictureUrl" value="reward_noimage.png" />
                    <a onclick="ShowCustomCrop()" class="reward-img-edit"><i class="fa-solid fa-lg fa-pen-to-square text-warning"></i></a>
                </div>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <textarea asp-for="Description" rows="3" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-sm-12">
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </div>

    </form>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VisionBoard/Views/Rewards/Delete.cshtml
@model VisionBoard.Models.Reward

@{
    ViewData["Title"] = "Delete";
    Layout = null;
}


<h3>Are you sure you want to delete this?</h3>
<div class="row m-4">
    <div class="col-md-12">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12 text-center">
                    <div class="col-md-8 p-3">
                        <div>
                            <img src=@("~/images/" + (Model.PictureUrl ?? "reward_noimage.png")) asp-append-version="true" class="goal-img">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-md-12">
                    <span class="label font-weight-bold">Name : </span>
                    <span>@Model.Name </span>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-md-12">
                    <span class="label font-weight-bold">Goal : </span>
                    <span>@(Model.Goal==null?"":Model.Goal.Name)</span>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-md-12">
                    <span class="label font-weight-bold">Status : </span>
                    <span>@(Model.Status==true?"Completed":"Pending")</span>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-sm-12">
                    <a class="btn btn-danger" onclick="DeleteReward('@Url.Action("Delete", "Rewards", new { id=@Model.Id, source=@ViewBag.Source})')">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>

VisionBoard/Views/Rewards/Details.cshtml
@model VisionBoard.Models.Reward

@{
    ViewData["Title"] = "Details";
    Layout = null;
}

<div class="row m-4">
    <div class="col-md-12">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12 text-center">
                    <div class="col-md-8 p-3">
                        <div>
                            <img src=@("~/images/" + (Model.PictureUrl ?? "reward_noimage.png")) asp-append-version="true" class="goal-img">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-md-12">
                    <span class="label font-weight-bold">Name : </span>
                    <span>@Model.Name </span>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-md-12">
                    <span class="label font-weight-bold">Goal : </span>
                    <span>@(Model.Goal==null?"":Model.Goal.Name)</span>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-md-12">
                    <span class="label font-weight-bold">Status : </span>
                    <span>@(Model.Status==true?"Completed":"Pending")</span>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-md-12">
                    <span class="label font-weight-bold">Description : </span>
                    <span>@Model.Description </span>
                </div>
            </div>
        </div>
    </div>
</div>

VisionBoard/Views/Rewards/Edit.cshtml
@model VisionBoard.Models.Reward

@{
    ViewData["Title"] = "Edit";
    Layout = null;
}


<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-12 text-center">
                <div id="crop-reward-image" style="display:none">
                    @await Html.PartialAsync("~/Views/Media/CustomCrop.cshtml", "RewardImage")
                </div>
            </div>
        </div>
        <form asp-controller="Rewards" asp-action="Edit" onsubmit="return AddorEditReward(this);">
            <input type="hidden" name="source" id="source" value="@ViewBag.Source" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-12 text-center">
                    <div class="reward-img">
                        <img src=@("../../images/" + (Model.PictureUrl ?? "reward_noimage.png"))asp-append-version="true" id="reward-img">
                        <input type="hidden" id="reward-picture-url" name="PictureUrl" value="reward_noimage.png" />
                        <a onclick="ShowCustomCrop()" class="reward-img-edit"><i class="fa-solid fa-lg fa-pen-to-square text-warning"></i></a>
                    </div>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea asp-for="Description" rows="3" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <div class="form-group form-check">
                            <span class="control-label">Status </span>
                            <label class="radio-inline pl-2">
                                <input type="radio" name="Status" value="true" @(Model.Status ? "Checked" : "")>Completed
                            </label>
                            <label class="radio-inline pl-2">
                                <input type="radio" name="Status" value="false" @(!Model.Status ? "Checked" : "")>Pending
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-sm-12">
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VisionBoard/Views/Rewards/Index.cshtml
@model IEnumerable<VisionBoard.Models.Reward>

@{
    ViewData["Title"] = "Index";
}
<div class="mt-4">
    <h2>Rewards</h2>
    <div class="mt-4">
        <div id="list-rewards" class="rewards-table">
            @await Html.PartialAsync("IndexRewards", Model)
        </div>
    </div>
</div>

VisionBoard/Views/Rewards/IndexRewards.cshtml
@model IEnumerable<VisionBoard.Models.Reward>

@{
    ViewData["Title"] = "Index";
}

<table class="table">
    <thead>
        <tr>
            <th width="20%">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th width="35%">
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th width="20%">
                @Html.DisplayNameFor(model => model.Goal)
            </th>
            <th width="10%">
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th width="15%">
                <a onclick="showInPopup('@Url.Action("Create", "Rewards", null, Context.Request.Scheme)','Add Reward')" class="btn btn-success text-white"> Add Reward</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="col-description">
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>@(item.Goal==null?"":item.Goal.Name)</td>
                <td>
                    @Html.Label("Status", item.Status ? "Completed" : "Pending")
                </td>
                <td>
                    <a onclick="showInPopup('@Url.Action("Edit","Rewards",new { id = @item.Id },Context.Request.Scheme)','Edit Reward')"><i class="fa-solid fa-pen-to-square text-warning"></i></a>
                    <a onclick="showInPopup('@Url.Action("Details","Rewards", new { id = @item.Id }, Context.Request.Scheme)','View Reward')"><i class="fa-solid fa-eye text-info pl-2"></i></a>
                    <a onclick="showInPopup('@Url.Action("Delete","Rewards", new { id = @item.Id }, Context.Request.Scheme)','Delete Reward')"><i class="fa-solid fa-trash-can text-danger pl-2"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>