VisionBoard/Controllers/GoalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Net.Http.Headers;
using VisionBoard.DAL;
using VisionBoard.Models;
using VisionBoard.Utilis;

namespace VisionBoard.Controllers
{
    public class GoalsController : Controller
    {
        private readonly IGoalRepository goalsRepo;
        private readonly IRewardRepository rewardRepo;
        private readonly ITagRepository tagRepo;
        private readonly IErrorLogRepository errorLogRepository;
        private readonly IHostingEnvironment hostingEnvironment;

        public GoalsController(IGoalRepository goalsRepo, IRewardRepository rewardRepo, ITagRepository tagRepo, IErrorLogRepository errorLogRepository, IHostingEnvironment hostingEnvironment)
        {
            this.goalsRepo = goalsRepo;
            this.rewardRepo = rewardRepo;
            this.tagRepo = tagRepo;
            this.errorLogRepository = errorLogRepository;
            this.hostingEnvironment = hostingEnvironment;
        }


        // GET: Goals
        public async Task<IActionResult> Index(int[] tagIds)
        {
            try
            {
                var goals = await goalsRepo.GetAllGoals(tagIds);
                ViewData["TagId"] = new SelectList(await tagRepo.GetAllTags(), "Id", "Name");
                string requestType = Request.Headers[HeaderNames.XRequestedWith];

                if (requestType == "XMLHttpRequest")
                {
                    return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "IndexGoals", goals) });
                }
                else
                {
                    return View(goals);
                }

            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Goals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                var goal = await goalsRepo.GetGoal((int)id);

                if (goal == null)
                {
                    return NotFound();
                }

                return View(goal);
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Goals/Create
        public async Task<IActionResult> Create()
        {
            try
            {
                ViewData["RewardId"] = new SelectList(await rewardRepo.GetAllRewards(), "Id", "Name");
                ViewData["TagId"] = new SelectList(await tagRepo.GetAllTags(), "Id", "Name");
                return View();
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,StartOn,EndingOn,Magnitude,PictureUrl,TagIds,RewardId")] CreateGoal createGoal)
        {
            try
            {
                Goal goal = null;
                List<GoalTags> goalTags = null;
                //goal completed or not
                createGoal.Status = false;

                if (ModelState.IsValid)
                {
                    if (createGoal.TagIds.Length > 0)
                    {
                        goalTags = createGoal.TagIds.Select(t => new GoalTags() { GoalId = createGoal.Id, TagId = t }).ToList();
                    }

                    goal = new Goal()
                    {
                        Name = createGoal.Name,
                        Description = createGoal.Description,
                        StartOn = createGoal.StartOn,
                        EndingOn = createGoal.EndingOn,
                        Magnitude = createGoal.Magnitude,
                        PictureUrl = createGoal.PictureUrl,
                        GoalTags = goalTags,
                        RewardId = createGoal.RewardId
                    };

                    await goalsRepo.AddGoal(goal);
                    return RedirectToAction("Details", new { id = goal.Id });
                }
                ViewData["RewardId"] = new SelectList(await rewardRepo.GetAllRewards(), "Id", "Name", goal.RewardId);
                ViewData["TagId"] = new SelectList(await tagRepo.GetAllTags(), "Id", "Name");
                return View(goal);

            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Goals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var goal = await goalsRepo.GetGoal((int)id);

                if (goal == null)
                {
                    return NotFound();
                }
                int[] TagIds = goal.GoalTags.Select(gt => gt.TagId).ToArray();
                ViewData["TagId"] = new MultiSelectList(await tagRepo.GetAllTags(), "Id", "Name", TagIds);
                ViewData["RewardId"] = new SelectList(await rewardRepo.GetAllRewards(), "Id", "Name", goal.RewardId);
                return View(goal);
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // POST: Goals/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, int[] TagIds,[Bind("Id,Name,Description,StartOn,EndingOn,Magnitude,PictureUrl,MeasurementId,TagId,RewardId,Status")] Goal goal)
        {
            try
            {
                if (id != goal.Id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    if (TagIds.Length > 0)
                    {
                        goal.GoalTags = TagIds.Select(t => new GoalTags() { GoalId = goal.Id, TagId = t }).ToList();
                    }
                    await goalsRepo.UpdateGoal(goal);
                    return RedirectToAction(nameof(Index));
                }
                TagIds = goal.GoalTags.Select(gt => gt.TagId).ToArray();
                ViewData["TagId"] = new MultiSelectList(await tagRepo.GetAllTags(), "Id", "Name", TagIds);
                ViewData["RewardId"] = new SelectList(await rewardRepo.GetAllRewards(), "Id", "Name", goal.RewardId);
                return View(goal);
            }
            catch (Exception ex)
            {
                if (!await GoalExists(goal.Id))
                {
                    return NotFound();
                }
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Goals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var goal = await goalsRepo.GetGoal((int)id);

                if (goal == null)
                {
                    return NotFound();
                }

                return View(goal);
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // POST: Goals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var goal = await goalsRepo.DeleteGoal(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        private async Task<bool> GoalExists(int id)
        {
            try
            {
                return await goalsRepo.IsGoalExist(id);
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return false;

        }


    }
}

VisionBoard/Controllers/TagsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VisionBoard.DAL;
using VisionBoard.Models;
using VisionBoard.Utilis;

namespace VisionBoard.Controllers
{
    public class TagsController : Controller
    {
        private readonly ITagRepository tagRepository;
        private readonly IErrorLogRepository errorLogRepository;

        public TagsController(ITagRepository tagRepository, IErrorLogRepository errorLogRepository)
        {
            this.tagRepository = tagRepository;
            this.errorLogRepository = errorLogRepository;
        }


        // GET: Tags
        public async Task<IActionResult> Index()
        {
            try
            {
                var tags = await tagRepository.GetAllTags();
                return View(tags);
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Tags/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                if (id != null)
                {
                    var tag = await tagRepository.GetTag((int)id);

                    if (tag != null)
                    {
                        return View(tag);
                    }
                }
                return NotFound();
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Tags/Create
        public async Task<IActionResult> Create(string source)
        {
            try
            {
                ViewBag.Source = source;
                return View();
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // POST: Tags/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string source, [Bind("Id,Name,Colour")] Tag tag)
        {
            try
            {
                //tag active or not
                tag.Status = true;

                if (ModelState.IsValid)
                {
                    var newTag = await tagRepository.AddTag(tag);

                    if (source == "DropDown")
                    {
                        return Json(new { isValid = true, Source = source, Id = newTag.Id, Name = newTag.Name });
                    }
                    else
                    {
                        var tags = await tagRepository.GetAllTags();
                        return Json(new { isValid = true, source = "Index", html = Helper.RenderRazorViewToString(this, "IndexTags", tags) });
                    }
                }

                return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Create", tag) });
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Tags/Edit/5
        public async Task<IActionResult> Edit(int? id, string source)
        {
            try
            {
                if (id != null)
                {
                    var tag = await tagRepository.GetTag((int)id);

                    if (tag != null)
                    {
                        ViewBag.Source = source;
                        return View(tag);
                    }
                }

                return NotFound();
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // POST: Tags/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, string source, [Bind("Id,Name,Colour")] Tag tag)
        {
            try
            {
                if (id != tag.Id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    tag.Status = true;
                    var newTag = await tagRepository.UpdateTag(tag);

                    if (source == "DropDown")
                    {
                        return Json(new { isValid = true, Source = source, Id = newTag.Id, Name = newTag.Name });
                    }
                    else
                    {
                        var tags = await tagRepository.GetAllTags();
                        return Json(new { isValid = true, source = "Index", html = Helper.RenderRazorViewToString(this, "IndexTags", tags) });
                    }

                }
                return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", tag) });
            }
            catch (Exception ex)
            {
                if (!await TagExists(tag.Id))
                {
                    return NotFound();
                }
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // GET: Tags/Delete/5
        public async Task<IActionResult> Delete(int? id, string source)
        {
            try
            {
                if (id != null)
                {
                    var tag = await tagRepository.GetTag((int)id);

                    if (tag != null)
                    {
                        ViewBag.Source = source;
                        return View(tag);
                    }
                }
                return NotFound();
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id, string source)
        {
            try
            {
                var newTag = await tagRepository.DeleteTag(id);
                if (source == "DropDown")
                {
                    return Json(new { isValid = true, Source = source, Id = newTag.Id, Name = newTag.Name });
                }
                else
                {
                    var tags = await tagRepository.GetAllTags();
                    return Json(new { isValid = true, source = "Index", html = Helper.RenderRazorViewToString(this, "IndexTags", tags) });
                }
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return View("../Shared/Error", null);

        }


        private async Task<bool> TagExists(int id)
        {
            try
            {
                return await tagRepository.IsTagExist(id);
            }
            catch (Exception ex)
            {
                await errorLogRepository.AddErrorLog(ex.TargetSite.ReflectedType.DeclaringType.Name, ex.TargetSite.ReflectedType.Name, ex.Message);
            }
            return false;

        }


    }
}

VisionBoard/Views/Goals/Create.cshtml
@model VisionBoard.Models.CreateGoal

@{
    ViewData["Title"] = "Create";
}

<div class="row mt-5">
    <h3 class=" p-2">New Goal</h3>
    <hr />
    <div class="col-md-12">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-8">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label asp-for="Name" class="control-label"></label>
                                    <input asp-for="Name" class="form-control" />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label asp-for="Description" class="control-label"></label>
                                    <textarea asp-for="Description" rows="5" class="form-control"></textarea>
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="goal-img">
                        <img src="~/images/noimage.png" asp-append-version="true" name="PictureUrl" id="goal-image" class="goal-img">
                        <input type="hidden" asp-for="PictureUrl" />
                        <a onclick="showInPopup('@Url.Action("CustomCrop","Media", new { source = "GoalImage" }, Context.Request.Scheme)','Drag image to adjust')" class="edit-btn"><i class="fa-solid fa-lg fa-pen-to-square text-warning"></i></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="row align-items-end">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="StartOn" class="control-label"></label>
                                <input asp-for="StartOn" class="form-control" />
                                <span asp-validation-for="StartOn" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="EndingOn" class="control-label"></label>
                                <input asp-for="EndingOn" class="form-control" />
                                <span asp-validation-for="EndingOn" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div label class="pt-1 control-label"><label for="Magnitude">Importance </label></div>
                                <div class="p-2"><input name="Magnitude" type="range" class="form-range w-75" value="0" min="0" max="5" id="Magnitude" oninput="this.nextElementSibling.value = this.value"><output class="pl-2 font-weight-bold">0</output></div>
                                <span asp-validation-for="Magnitude" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="pt-1">
                                    <span for="TagIds" class="control-label">Tags </span>
                                </div>
                                <select id="tagDropDownList" name="TagIds" asp-items="ViewBag.TagId" multiple="multiple" class="form-control"></select>
                                <a onclick="showInPopup('@Url.Action("Create", "Tags", new { source = "DropDown" }, Context.Request.Scheme)','Add Tag')" class="p-2"><i class="fa-solid fa-lg fa-circle-plus text-success"></i></a>
                                @*<a onclick="EditTagFromDropdown('@Url.Action("Edit","Tags", new { source = "DropDown" }, Context.Request.Scheme)','Edit Tag')" class="p-2"><i class="fa-solid fa-eye text-info"></i></a>
                                    <a onclick="DeleteTagFromDropdown('@Url.Action("Delete","Tags", new { source = "DropDown" }, Context.Request.Scheme)')" class="p-2"><i class="fa-solid fa-trash-can text-danger"></i></a>*@


                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="row align-items-end">
                                <div class="col-md-8">
                                    <label asp-for="RewardId" class="control-label"></label>
                                    <select asp-for="RewardId" class="form-control" asp-items="ViewBag.RewardId"></select>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <a onclick="showInPopup('@Url.Action("Create", "Rewards", new { source = "DropDown" }, Context.Request.Scheme)','Add Reward')" class="p-2"><i class="fa-solid fa-circle-plus fa-lg text-success"></i></a>
                                        <a onclick="EditRewardFromDropdown('@Url.Action("Edit","Rewards", new { source = "DropDown" }, Context.Request.Scheme)','Edit Reward')" class="p-2"><i class="fa-solid fa-lg fa-pen-to-square text-warning"></i></a>
                                        <a onclick="DeleteRewardFromDropdown('@Url.Action("Delete","Rewards", new { source = "DropDown" }, Context.Request.Scheme)')" class="p-2"><i class="fa-solid fa-lg fa-trash-can text-danger"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });
        });

        $('#tagDropDownList').multiselect();
    </script>
}

VisionBoard/Views/Goals/Delete.cshtml
@model VisionBoard.Models.Goal

@{
    ViewData["Title"] = "Delete";
    Layout = null;
}

<h3>Are you sure you want to delete this?</h3>

<div class="row mt-5 mb-5">
    <div class="col-md-12">
        <div class="row">
            <div class="col-sm-12">
                <span class="h5">@Model.Name</span>
            </div>
        </div>
    </div>
</div>
<div>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
</div>

VisionBoard/Views/Goals/Details.cshtml
@model VisionBoard.Models.Goal

@{
    ViewData["Title"] = "Details";
}

@Html.Hidden("GoalId", Model.Id)
<div class="row mt-5">
    <div class="col-md-12">
        <div class="row">
            <div class="col-sm-8">
                <h3>@Model.Name</h3>
            </div>
            <div class="col-sm-4">
                <div>
                    @foreach (GoalTags goaltag in Model.GoalTags)
                    {
                        <span class="badge" style="padding:5px;background-color: @goaltag.Tag.Colour">
                            @goaltag.Tag.Name
                        </span>
                    }
                </div>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-8">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-12">
                            <span class="label font-weight-bold">Description : </span>
                            <span>@Model.Description </span>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-md-6">
                            <span class="label font-weight-bold">Started On : </span>
                            <span>@Model.StartOn.Date.ToString("dd/MM/yyyy")</span>
                        </div>
                        <div class="col-md-6">
                            <span class="label font-weight-bold">Due On : </span>
                            <span>@Model.EndingOn.Value.Date.ToString("dd/MM/yyyy")</span>
                        </div>
                    </div>
                    <div class="row p-2">
                        <div class="col-md-12">
                            <span class="label font-weight-bold">Importance : </span>
                            @{
                                for (int i = 0; i < 5; i++)
                                {
                                    if (i < @Model.Magnitude)
                                    {
                                        <span class="fa fa-circle text-warning"></span>
                                    }
                                    else
                                    {
                                        <span class="fa fa-circle"></span>
                                    }
                                }
                            }
                        </div>
                    </div>
                    <div class="row p-2">
                        <div class="col-md-12">
                            <span class="label font-weight-bold">Status : </span>
                            <span>@(Model.Status==true?"Completed":"Pending")</span>
                        </div>
                    </div>
                    @{
                        if (Model.Reward != null)
                        {
                            <div class="row p-2">
                                <div class="col-md-12">
                                    <span class="label font-weight-bold">Reward : </span>
                                    <span>@Model.Reward.Name</span>
                                </div>
                            </div>

                        }
                    }
                    <div class="row p-2">
                        <div class="col-md-12">
                            <span class="label font-weight-bold">Track Progress : </span>
                            <label class="radio-inline pl-2">
                                <input type="radio" name="TrackProgress" @(Model.Measurement != null ? "Checked" : "") value="Yes">Yes
                            </label>
                            <label class="radio-inline pl-2">
                                <input type="radio" name="TrackProgress" value="No" @(Model.Measurement == null ? "Checked" : "")>No
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div id="show-progress" class="show-measurement">
                                @if (Model.Measurement != null)
                                {
                                    @await Html.PartialAsync("~/Views/Measurements/Details.cshtml", Model.Measurement)
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div>
                    <img src=@("~/images/" + (Model.PictureUrl ?? "noimage.png")) asp-append-version="true" class="goal-img">
                </div>
            </div>
        </div>
        <div class="row p-2">
            <div class="col-sm-12">
                <div id="steps-table" class="steps-table">
                    @await Html.PartialAsync("~/Views/Steps/IndexSteps.cshtml", Model.Steps, new ViewDataDictionary(ViewData) { { "goalId", Model.Id } })
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model.Id">Edit</a> |
    <a onclick="showInPopup('@Url.Action("Delete","Goals", new { id = Model.Id }, Context.Request.Scheme)','Delete Goal')" class="btn btn-danger">Delete</a>
</div>